# ############################################################################
# Environmental and Experiment parameters
# ############################################################################

cluster: ai  # 'ai' or 'rcc'
dataset_name: librispeech  # 'librispeech' or 'radio' or 'atczero'
num_train: 1024

