# ############################################################################
# Environmental and Experiment parameters
# ############################################################################

cluster: ai  # 'ai' or 'rcc'
dataset_name: police  #'librispeech' or 'police' or 'atczero'
num_train: null
num_sec: 28800
# XXX: Make this user-independent and somehow dependent on the cluster!
scratch_dir: /net/projects/uri/ra/echandler/scratch
#scratch_dir: /project/graziul/ra/echandler/scratch

