# ############################################################################
# Environmental and Experiment parameters
# ############################################################################

cluster: rcc  # 'ai' or 'rcc'
dataset_name: atc0  # 'librispeech' or 'radio' or 'atczero'
num_train: None
num_sec: 1800
# XXX: Make this user-independent and somehow dependent on the cluster!
scratch_dir: /project/graziul/ra/echandler/scratch

