#!/bin/bash

#
# USAGE:
# From the terminal, run:
# sbatch run-training.job <path_to_conda_env>
#

#
#OPIONS FOR JOB ID:
#SBATCH --job-name=train-asr
#
#OPTIONS FOR EMAIL:
#SBATCH --mail-user=%u@uchicago.edu
#SBATCH --mail-type=ALL
#SBATCH --output=/project/graziul/ra/%u/slurm_output/%j.%N.stdout
#SBATCH --error=/project/graziul/ra/%u/slurm_output/%j.%N.stderr
#
#OPTIONS FOR PARTITION:
#SBATCH --account=pi-graziul
#
#OPTIONS FOR JOB SIZE:
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --partition=gpu
#SBATCH --gpus-per-task=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=10000
#SBATCH --time=01:00:00
#

env_dir="$1"

if [ ! -e "$env_dir" ];
then
    echo "Conda environment not found. See 'create_env.sh'. Exiting."
    exit 1
fi

echo "Activating conda"
source 'conda_bashrc'
conda activate "$env_dir"

echo "Running model"
python train_deepspeech.py
