#!/bin/bash

#
# USAGE:
# From the terminal, run:
# sbatch run-training.job <path_to_conda_env>
#

#
#OPIONS FOR JOB ID:
#SBATCH --job-name=train-asr
#
#OPTIONS FOR EMAIL:
#SBATCH --output=/project/graziul/ra/%u/slurm_output/%j.%N.stdout
#SBATCH --error=/project/graziul/ra/%u/slurm_output/%j.%N.stderr
#
#OPTIONS FOR PARTITION:
#SBATCH --account=pi-graziul
#
#OPTIONS FOR JOB SIZE:
#SBATCH --partition=gpu
# Always set ntasks==gpus and ntasks-per-gpu=1
#SBATCH --nodes=1
#SBATCH --gpus=2
#SBATCH --ntasks=2
#SBATCH --ntasks-per-gpu=1
#SBATCH --mem-per-cpu=40G
#SBATCH --time=06:00:00
#

env_dir="$1"

if [ ! -e "$env_dir" ];
then
    echo "Conda environment not found. See 'create_env.sh'. Exiting."
    exit 1
fi

echo "Activating conda"
source 'env/conda_bashrc'
conda activate "$env_dir"

echo "Listing gpu nodes"
sh show_cuda_devices.sh

python tf_devices.py
echo "Running model"
# TODO: make these command line args
dataset='radio'
output_dir='/project/graziul/ra/echandler'
radio_dir='/project/graziul/transcripts'
libri_dir='/project/graziul/ra/shiyanglai/experiment1/audio data/LibriSpeech/train-clean-100/'
python train_deepspeech.py "$dataset" "$radio_dir" "$output_dir"

